
# coding: utf-8

# <div align="right">Python 2.7 Jupyter Notebook</div>
# 
# # Living labs
# <br>
# <div class="alert alert-warning">
# <b>This notebook should be opened and completed by students completing both the technical and non-technical tracks of this course.</b>
# </div>
# 
# ### Your completion of the notebook exercises will be graded based on your ability to:
# 
# > **Understand**: Do your comments show evidence that you recall and understand technical concepts?

# # Notebook introduction
# 
# Living labs describe the paradigm of working with new ideas and technology, directly engaging with, and observing users while they are living their lives.
# 
# While the levels of direct user engagement and co-creation vary between the examples referenced in this section, they share the access to users behavior in response to novel products, content or activity.

# # 1. Living Labs
# 
# A living lab can be established using existing infrastructure and data sources. This was shown in the example of the Andorra living lab which made use of CDRs, credit card transactions, and public transportation data. While direct user engagement may be limited, their behaviors - especially their reactions to new products or experimental interventions - can be observed in this setting. Living labs can also be entirely virtual, as is the case in the A/B testing of web applications.
# 
# Although the bleeding edge of living lab development is driven by the growing data collection and interaction capabilities that have been enabled by the spread of ubiquitous computing, this is not a prerequisite for big or electronic data. In Video 2 Professor Alex Pentland discusses an example of how Nike leverages living labs to determine which shoes to release within their stores. You can also refer to [Hack-MIT](http://livinglab.mit.edu/hack-mit/) as an example of how to use existing infrastructure, such as WiFi access points, as a simple living lab.
# 
# Data visualization can take many forms. You can refer to [this](https://github.com/hariharsubramanyam/mit-wifi-data-vis) example of a visualization of WiFi data. Once you have the basic lab in place, you would generally build your use case around it. Marketers would likely be interested in the density and profiles of individuals in specific areas, and the resulting efficiency of campaigns or other interventions, while city planners may be interested in optimizing flow in public spaces.
# 
# All of the data that was used in this course was generated by sophisticated deployments which collected not only **big** data, but also **deep** data. 
# 
# 
# Another recent trend in technology, the "[Internet of Things](http://www.gartner.com/it-glossary/internet-of-things/)" (or "IoT"), holds significant opportunities for data collection and interaction with the environment, whether human or device based. The big shift here is that the end-points are becoming active and they contain computation capabilities, where previous efforts focused on sensors or observations alone.
# 
# > **Note**: The presence of computation capabilities at the end-points also opens up opportunities such as software-defined products. Consider activity trackers learning to recognize new activities, or self-driving cars where new features such as parking capabilities can be added with software updates. Once you have gathered data and refined your algorithms, these can potentially be implemented as software-defined products or features (like the one above) can be added using this mechanism.
# 
# You can read more about the European Open Living Labs network [here](http://www.openlivinglabs.eu/), and another example of a recent deployment of a living lab using sensor and mobile data, the Amsterdam IoT Living Lab, [here](http://iotlivinglab.com/). Additional information is available [here](http://iotlivinglab.com/amsterdam-iot-living-lab-wiki/) and on this [blog](https://www.yenlo.com/blog/building-the-world-s-biggest-ibeacon-living-lab-with-wso2).
# 
# > **Note**: 
# 
# > Living lab projects typically include a wide variety of stakeholders and partners, including government, academic, and commercial parties. Refer to the goal statement of the Amsterdam Smart City project below as an example:
# 
# > **Goal**: The goal of the IoT Living Lab is to provide IoT infrastructure and actionable, Open Data, and developer friendly platforms for emerging IoT innovations. This stimulates the creation of new startups and mobile applications, which in turn make a rapid impact on the local economy.
# 
# > (Source: Amsterdam Smart City 2016)
# 
# While the focus of this course is social analytics, there are a number of recent technological trends that can add significant value to your future projects. You are encouraged to explore these on your own.
# 
# Much of the publicity around big data focuses solely on the volume, or in some cases the format of the data, and many fail to capitalize on existing sources of data that may already be accessible. [Dark data](http://www.gartner.com/it-glossary/dark-data/) refers to data that is already available, but not utilized. IoT also contains a number of relevant concepts. You can read about Gartner's view of the top ten IoT technologies for 2017 and 2018 [here](http://www.gartner.com/newsroom/id/3221818).

# > **Note**: 
# 
# > Once you better understand the available data sources, as well as the options offered by technological developments, you will be in a much better position to successfully start and complete your social analytics projects.
# 
# Refer to the additional links below for more guidance:
# - [The Dark Side of Big Data](http://www.forbes.com/sites/tomfgoodwin/2016/07/14/the-dark-side-of-big-data/#16e565e738a2)
# - [Understanding Dark Data](https://www.linkedin.com/pulse/20140529034348-246665791-understanding-dark-data)
# - [Avoiding The Pitfalls of Dark Data](http://www.forbes.com/sites/centurylink/2015/10/09/watch-your-step-avoiding-the-pitfalls-of-dark-data/#3ce31cf278c4)

# <div class="alert alert-info">
# <b>Exercise 1 Start.</b>
# </div>
# 
# ### Instructions
# 
# > Arek Stopczynski points out the dangers of fixating on big data and losing perspective, and studying the data instead of the population of interest (and their interactions).
# 
# > a) How do "deep data" and "living labs" help us to avoid the pitfalls of only studying available data sets?
# 
# > b) List some of the advantages of "living labs" as opposed to "focus groups" or "large scale surveys"?
# 
# > **Note**: Your answer should be a short description (two to three sentences) for each of the two questions.

# **a)** If scientifically defined and planned, and responding to ethical and privacy concerns, they give an opportunity to study the behavior of subjects through a combination of data collection channels in a customized way and in real time and space with minimal intrusion on their daily habits and a minimum of influences letting the information come from them directly instead of extracting from rigid available data sets by definition non recent, not always relevant information even for the best proxies, with rarely appropriate ranges, sometimes questionable robustness and reliability. It also allow to control the data collection process, treatment and interpretation to avoid data integrity and privacy issues and make sure that the process if reproducible.
# 
# **b)** A few examples of advantages in favor of living labs:
# - Living labs are often multi-channels vs. single or limited channels for focus groups or surveys.
# - Living labs are live and can be ran on long periods of time vs. one time takes for focus groups and surveys.
# - Living labs are direct expression without inferences of users behaviors vs. one time opinions in focus groups and surveys.
# - Living labs can go beyond focus groups and surveys by looking at actual actions of subjects and not only what they say.
# - Living labs can avoid biases infered by the context, questions or the delivery of questions in focus groups or surveys.

# <br>
# <div class="alert alert-info">
# <b>Exercise 1 End.</b>
# </div>
# 
# > **Exercise complete**:
#     
# > This is a good time to "Save and Checkpoint".

# ## 1.1 Purpose
# Typical purposes for setting up living labs include:
# * Research;
# * Development; and
# * Production applications.
# 
# In commercial context, there are internal and external opportunities for setting up living labs.
# 
# ### 1.1.1 External
# Typical uses include marketing and customer insight use cases where the profile and demographics of individuals are used to optimize or create product or service offerings. These insights are typically also relevant in supply chain optimization.
# 
# ### 1.1.2 Internal
# A better understanding of social networks in companies can be used in human resources projects, as per the examples introduced in Module 7. You can also refer to the seminal work of Professor Alex Pentland, the [Sociometric Badge study](http://realitycommons.media.mit.edu/badgedataset.html) from 2008, which provides a myriad of insights in this [paper](http://realitycommons.media.mit.edu/download.php?file=Sensible_Organizations.pdf).
# 
# Organizations usually have access to large amounts of dark and deep data which can be utilized to get started. These sources of data can also be extended with applications such as Funf to create deep data sets.
# 
# > **Note**: 
# 
# > Data privacy and sovereignty
# 
# > It is hard to overemphasize the importance of the data privacy, or even data sovereignty of individuals, due its centrality in building the trust relationship necessary for a living lab to be successful. Please review the privacy course content from Module 6, with special focus on the open Personal Data Store (openPDS) architecture, which strives to provide privacy to the users even when the data is used for internal purposes only.

# <div class="alert alert-info">
# <b>Exercise 2 Start.</b>
# </div>
# 
# ### Instructions
# 
# > In Video 4, David Shrier discusses the typical stakeholders involved in setting up living labs. Please provide a short summary of the roles played by each of the following parties, referencing both the input (what they require from the other parties) and the output that they deliver to the other stakeholders.
# 
# > a) Government 
# 
# > b) Data partners
# 
# > c) Local or global business 
# 
# > d) Local universities or academic partners

# **a)** Government: under the pre-requisite that the study follow existing local, national and international laws and regulations in data ethics, privacy and use:
# - Local community introduction and engagement support
# - Financing subsidies in setting up and building the living lab
# - Local stakeholders introductions and involvement of governmental, local, national or international organizations and agencies
# - Offer credibility for potential study subjects
# - Help in developping use cases and finance follow up programs
# 
# **b)** Data partners: under the pre-requisite that the study respect client database privacy and use standards:
# - Help in designing the study method and data collect (telcommunication or credit card companies)
# - Help in sampling methodology in regard to available data
# - Can sponsor mobile phones or equipments to gain exposure, text new products/services and gain competitive intelligence through the study (subjects choices of data or voice plans, deep data consumption habits insights, etc.) if only the equipment given with no strings attached
# - Industry expertise and technical support
# - Help in scaling the study on larger range from local to national and even international scale.
# 
# **c)** Local or global business: uder the pre-requisite that the study can have meaningful insights for them:
# - On the ground support
# - Data analysis support
# - Financial support if no strings attached
# 
# **d)** Local universities or academic partners: under the pre-requisite that the study corresponds to their ethics, data privacy and scientific standards:
# - Methodology support
# - Data analysis support
# - Scientific community exposure
# - Scientific credibility

# <br>
# <div class="alert alert-info">
# <b>Exercise 2 End.</b>
# </div>
# 
# > **Exercise complete**:
#     
# > This is a good time to "Save and Checkpoint".

# <div class="alert alert-info">
# <b>Exercise 3 Start.</b>
# </div>
# 
# ### Instructions
# 
# > Professor Alex Pentland discussed how many organizations are realizing the value of data as a strategic asset. How does the role of an analyst change when considering strategic analysis as opposed to more traditional data analysis?
# 
# > Provide a short description of the typical tasks that you would expect within this new role, and briefly discuss or refer to potential organizational changes (or parties) that the analysts would need to interact with in their new role.

# The strategic analyst supports the company management in the decision making process to shape the future of his company. He focuses more on competitive intelligence localizing and tracking the company in its competitive landscape, looking at market size and growth rate changes and their causation, threats of new entrants or substitute products or services, actionable user and consumer insights that could increase top and bottom line results in creating new products and services, or increase efficiency by reducing churn rates, switching rates, increase repeat customers, boost customers and partners satisfaction, improve marketing campaigns and delivery methods  efficiency or explore new payment options.
# 
# Duties will include:
# - Strategy formulation for the corporate management team and all its business units (assets and affiliates portfolio management and acquisitive growth)
# - Industry research, analysis and tracking
# - Growth opportunity identification and business case development
# - Pipeline development, specifically in the form of target identification, screening and tracking, and relationship development with potential targets 
# - Financial analysis and valuation 
# - Management of due diligence teams 
# - Business plan creation 
# - Deal structuring and negotiation 
# - Preparation of preliminary and final presentations to senior management 
# 
# Interactions should include:
# - Management team
# - Board of directors
# - Heads of units and key business units leaders
# - External consultants

# <br>
# <div class="alert alert-info">
# <b>Exercise 3 End.</b>
# </div>
# 
# > **Exercise complete**:
#     
# > This is a good time to "Save and Checkpoint".

# # 2. Submit your notebook
# 
# Please make sure that you:
# - Perform a final "Save and Checkpoint";
# - Download a copy of the notebook in ".ipynb" format to your local machine using "File", "Download as", and "IPython Notebook (.ipynb)", and
# - Submit a copy of this file to the online campus.
# 

# # 3. References
# Amsterdam Smart City. 2016. “IoT Living Lab - Amsterdam Smart City.” Accessed September 5. https://amsterdamsmartcity.com/projects/iot-living-lab. 
# 
# > **Note**:
# 
# > Arek Stopczynski references the Copenhagen Network Study and indicates that the research is ongoing. You can read more about recent developments and additional publications [here](https://sunelehmann.com/2016/08/24/new-paper-in-pnas/).

# In[ ]:



